### ISSUE TITLE
locate_motion_mode on does not show red box in overlay when storage a video file

### ISSUE THREAD

**Issue by Metus88** [Motion-Project/motion#1648]
### Did you read the guide?

Yes

### What is the base version number of Motion being used?

4.2.x

### What was the install method?

Installed via package tool

### What is base architecture?

Other

### What is the distro being used?

Ubuntu

### Disto version number

DOCKER IMAGE: OS Version Ubuntu 18.10 motionEye Version 0.42 Motion Versios 4.2.2	

### Camera type(s) being used?

Network camera with RTSP

### Describe the issue/problem and steps to reproduce

I used the docker image "ccrisan/motioneye:master-amd64" of motioneye with this config file of docker compose:
```
services:
  motioneye:
    container_name: motioneye
    image: ccrisan/motioneye:master-amd64
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/home/deb/DOCKER/motioneye:/etc/motioneye"
    - "/home/deb/DOCKER/motioneye/storage:/var/lib/motioneye"
    network_mode: host
    restart: unless-stopped
```
The operation system of the mini pc where docker is installed it is a Debian 11.6.0  amd64

If you configure a IP Network camera  RTSP and under "Video Device"->"Extra Motion Options" you write "locate_motion_mode on" and save, the video file stored when a motion is detected doesn't show the red lines/box overlay that I suppose have to appear. (I tried also with and without enable Text Overlay option.)
The documentation has to be update [locate motion mode](https://motion-project.github.io/motion_config.html#locate_motion_mode) or it's a bug?

### Relevant Motion log output (at log_level 8)

```shell
Before send my log level 8 I would like to know if it's a bug or only my misunderstanding of documentation.
Thanks
```
